name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Olá Galera da GFT Start Woman"
      - name: Print goodbye
        run: echo "Falou Galerinhaaaa"
